name: NormCI

# プルリクエスト or 手動実行 
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Normチェック
  norm:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout git repository
        uses: actions/checkout@v2
      
      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
        
      - name: Run Norminette
        run: norminette $(find . -type d -name test -prune -o -type f -regextype posix-basic -regex ".*\.\(c\|h\)" -print)
